/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        brand: ['Inter', 'sans-serif'],
        mono: ['JetBrains Mono', 'Courier New', 'monospace'],
      },
      fontWeight: {
        brand: '300',
      },
      letterSpacing: {
        brand: '0.4em',
      },
      colors: {
        // GateStatus 颜色（对齐 gate-* CSS 变量）
        gate: {
          block: {
            border: 'var(--gate-reject-border)',
            text: 'var(--gate-reject-foreground)',
            bg: 'var(--gate-reject)',
            icon: 'var(--gate-reject-foreground)',
          },
          warn: {
            border: 'var(--gate-confirm-border)',
            text: 'var(--gate-confirm-foreground)',
            bg: 'var(--gate-confirm)',
            icon: 'var(--gate-confirm-foreground)',
          },
          pass: {
            border: 'var(--gate-allow-border)',
            text: 'var(--gate-allow-foreground)',
            bg: 'var(--gate-allow)',
            icon: 'var(--gate-allow-foreground)',
          },
        },
        info: {
          date: 'var(--nara-glacier-foreground)',
          link: 'var(--foreground)',
          transport: {
            bg: 'var(--nara-glacier-muted)',
            text: 'var(--nara-glacier-foreground)',
            border: 'var(--nara-glacier-border)',
          },
        },
        'gate-allow': 'var(--gate-allow)',
        'gate-allow-foreground': 'var(--gate-allow-foreground)',
        'gate-allow-border': 'var(--gate-allow-border)',
        'gate-confirm': 'var(--gate-confirm)',
        'gate-confirm-foreground': 'var(--gate-confirm-foreground)',
        'gate-confirm-border': 'var(--gate-confirm-border)',
        'gate-suggest': 'var(--gate-suggest)',
        'gate-suggest-foreground': 'var(--gate-suggest-foreground)',
        'gate-suggest-border': 'var(--gate-suggest-border)',
        'gate-reject': 'var(--gate-reject)',
        'gate-reject-foreground': 'var(--gate-reject-foreground)',
        'gate-reject-border': 'var(--gate-reject-border)',
        'persona-abu': 'var(--persona-abu)',
        'persona-abu-foreground': 'var(--persona-abu-foreground)',
        'persona-abu-accent': 'var(--persona-abu-accent)',
        'persona-dre': 'var(--persona-dre)',
        'persona-dre-foreground': 'var(--persona-dre-foreground)',
        'persona-dre-accent': 'var(--persona-dre-accent)',
        'persona-neptune': 'var(--persona-neptune)',
        'persona-neptune-foreground': 'var(--persona-neptune-foreground)',
        'persona-neptune-accent': 'var(--persona-neptune-accent)',
        'trip-status-planning': 'var(--trip-status-planning)',
        'trip-status-planning-foreground': 'var(--trip-status-planning-foreground)',
        'trip-status-planning-border': 'var(--trip-status-planning-border)',
        'trip-status-progress': 'var(--trip-status-progress)',
        'trip-status-progress-foreground': 'var(--trip-status-progress-foreground)',
        'trip-status-progress-border': 'var(--trip-status-progress-border)',
        'trip-status-completed': 'var(--trip-status-completed)',
        'trip-status-completed-foreground': 'var(--trip-status-completed-foreground)',
        'trip-status-completed-border': 'var(--trip-status-completed-border)',
        'trip-status-cancelled': 'var(--trip-status-cancelled)',
        'trip-status-cancelled-foreground': 'var(--trip-status-cancelled-foreground)',
        'trip-status-cancelled-border': 'var(--trip-status-cancelled-border)',
        'budget-safe': 'var(--budget-safe)',
        'budget-safe-foreground': 'var(--budget-safe-foreground)',
        'budget-safe-border': 'var(--budget-safe-border)',
        'budget-warning': 'var(--budget-warning)',
        'budget-warning-foreground': 'var(--budget-warning-foreground)',
        'budget-warning-border': 'var(--budget-warning-border)',
        'budget-critical': 'var(--budget-critical)',
        'budget-critical-foreground': 'var(--budget-critical-foreground)',
        'budget-critical-border': 'var(--budget-critical-border)',
        'nara-lava': 'var(--nara-lava)',
        'nara-lava-foreground': 'var(--nara-lava-foreground)',
        'nara-lava-border': 'var(--nara-lava-border)',
        'nara-lava-muted': 'var(--nara-lava-muted)',
        'nara-glacier': 'var(--nara-glacier)',
        'nara-glacier-foreground': 'var(--nara-glacier-foreground)',
        'nara-glacier-border': 'var(--nara-glacier-border)',
        'nara-glacier-muted': 'var(--nara-glacier-muted)',
        'nara-tundra': 'var(--nara-tundra)',
        'nara-tundra-foreground': 'var(--nara-tundra-foreground)',
        'nara-tundra-border': 'var(--nara-tundra-border)',
        'nara-tundra-muted': 'var(--nara-tundra-muted)',
      },
    },
  },
  plugins: [],
}
